### ISSUE TITLE
Unnecessary large PDF versions of the logos.

### ISSUE THREAD

**Issue by dietmarw** [modelica/MA-Logos#2]
Currently the PDFs are extremely large and I'm not sure what the reason is for that. Using the SVGs and exporting them to PDF yields:
[Modelica_Language.pdf](https://github.com/modelica/MA-Logos/files/4230079/Modelica_Language.pdf)
 Which is 3.8 KB in size versus the current:
[Modelica_Language.pdf](https://github.com/modelica/MA-Logos/files/4230083/Modelica_Language.pdf) which is **926 KB** in size.
In addition the PDFs are the only ones with white padding. What is the reason for that?

**Comment by GallLeo** [comment]
I just checked: the PDFs are as delivered by the designers.
While the SVGs have been created by me based on EPS from Designers (using Inkscape).

I agree, that the PDFs have to much white padding and are a bit large. 
PDF file size is usually irrelevant, but not for PDFs to be used in pdflatex, as they increase the final file size.

We could replace the PDFs by newly generated ones. Probably we should use the EPS as a source to avoid multi-conversion?

**Comment by MartinOtter** [comment]
> We could replace the PDFs by newly generated ones. Probably we should use the EPS as a source to avoid multi-conversion?
Yes

**Comment by dietmarw** [comment]
@GallLeo can you take care of this?

**Comment by dietmarw** [comment]
@GallLeo What is the status here. Do I need to file a back-office ticket?
